# WorkshopC Configuration File

# Paths configuration
# third_party_includes are not affected by rules
third_party_includes:
  - external/
  - third_party/
  - vendor/
  - libs/
  - dependencies/

# Rules section
# Rules can be: Off, Warning, Error
rules:
  # Enum rule - forbids enum declarations
  enum:
    level: Warning

  # Private rule - forbids access of private struct fields
  private:
    level: Error
    private_field: _private
    setter_contains: pset
    getter_contains: pget

  # Typedef rule - requires typedef for all function pointers
  function_pointer:
    level: Warning

  # Assignment rule - require primitives to be assigned at declaration
  assignment:
    level: Warning
    forbid_null_assign: true
    forbid_null_as_arg: true
    forbid_zero_init_for_objects_with_pointers: true
    forbid_arg_reassign: true
    forbid_mut_arg_pointer: true

  # Prefix namespace rule - require header declarations to include folder structure in name
  prefix_namespace:
    level: Warning
    stop_at_dir: src
    stop_at_count: 10
    use_seperator: true
    seperator: __
    apply_to_functions: true
    apply_to_structs: true
    apply_to_typedefs: true
    require_ifndef_for_filepath: true
