// -------------------------------------------------------------
// A goto statement is never allowed, neither 'goto label;' nor the
// computed 'goto *address;' of GNU C. Labels on their own are not
// reported, only the jumps to them.
// -------------------------------------------------------------

#define JUMP_TO(label) goto label

void use(int value);

int forward_jump(int value)
{
    if (value < 0)
        goto done; // bad: a jump forward

    value = value * 2;

done: // good: a label is not a jump
    return value;
}

void backward_jump(void)
{
    int count = 0;

again:
    count++;

    if (count < 3)
        goto again; // bad: a jump backward, a hidden loop

    use(count);
}

void nested_jump(int rows, int columns)
{
    for (int row = 0; row < rows; ++row)
    {
        for (int column = 0; column < columns; ++column)
        {
            if (row * column > 10)
                goto out; // bad: breaking out of nested loops
        }
    }

out:
    use(rows);
}

void jump_through_macro(int value)
{
    if (value == 0)
        JUMP_TO(skip); // bad: a goto hidden in a macro

    use(value);

skip:
    use(0);
}

void computed_jump(int index)
{
    void *targets[] = { &&first, &&second };

    goto *targets[index & 1]; // bad: a computed goto

first:
    use(1);
    return;

second:
    use(2);
}

int suppressed_jump(int value)
{
    // WorkshopC off
    // Reason: a single cleanup path generated by an external tool
    if (value < 0)
        goto cleanup; // good: suppressed
    // WorkshopC on

    value = value * 2;

cleanup:
    return value;
}

int jump_after_suppression(int value)
{
    if (value > 100)
        goto clamp; // bad: the suppression was turned back on

    return value;

clamp:
    return 100;
}

void structured(int value)
{
    while (value > 0) // good: loops, break and continue are fine
    {
        if (value == 5)
            break;

        value--;
    }

    use(value);
}
